# @package _group_
lapa:
  root_dir: '/media/shrek/work/datasets/public/LaPa'

  train:
    image_dir: ${dataset.lapa.root_dir}/train/images
    label_dir: ${dataset.lapa.root_dir}/train/labels
    use_factor: 1.0

  val:
    image_dir: ${dataset.lapa.root_dir}/val/images
    label_dir: ${dataset.lapa.root_dir}/val/labels
    use_factor: 1.0

  test:
    image_dir: ${dataset.lapa.root_dir}/test/images
    label_dir: ${dataset.lapa.root_dir}/test/labels
    use_factor: 1.0
